
project_id = "ixkkrousepsiorwlaycp"

[functions.generate-storylines]
timeout = 300

[functions.generate-shots-for-scene]
timeout = 180

[functions.generate-character-image]
timeout = 300

[functions.generate-shot-image]
timeout = 300
